jobs:
  docker:
    if: github.ref_type == 'tag'
    name: Publish the image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: commit
        name: Get commit summary
        run: |
          ref=${{ github.ref }}
          version=${ref//refs\/tags\/v/}
          [ -z "$version" ] && exit 1
          echo "::set-output name=MAJOR_VERSION::$(echo $version | cut -d'.' -f1)"
          echo "::set-output name=MINOR_VERSION::$(echo $version | cut -d'.' -f-2)"
          echo "::set-output name=VERSION::$version"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          path: /tmp/.buildx-cache
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/llvm:${{ steps.commit.outputs.MAJOR_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/llvm:${{ steps.commit.outputs.MINOR_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/llvm:${{ steps.commit.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/llvm:latest
      - if: matrix.base_image != 'bullseye'
        name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.base_image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.base_image }}-new,mode=max
          context: .
          file: linux/${{ matrix.base_image }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/llvm:${{ matrix.base_image }}
      - name: Move cache
        run: |
          rm -fr /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Patch the description
        run: |
          DOCKERHUB_PASSWORD="${{ secrets.DOCKERHUB_PASSWORD }}" \
          DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" \
          tools/patch-dockerhub.sh llvm "Debian with the latest LLVM installed."
name: Publish
on:
  create:
    tags:
      - v[0-9]+(\.[0-9]+)*
