env:
  IMAGE_NAME: llvm
jobs:
  debian:
    name: debian:${{ matrix.dist }}
    needs:
      - ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Copy Dockerfile
        run: cp docker/linux/${{ matrix.dist }}/Dockerfile ./
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - id: current-time
        name: Format the current time
        run: |
          printf 'value=%s\n' $(date "+%Y%m%d%H%M%S") | tee -a $GITHUB_OUTPUT
      - name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.dist }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.current-time.outputs.value }}
      - id: overview
        name: Load README
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('node:fs')
            fs.readFile('README.md', {}, (err, data) => {
              if (err)
                core.setFailed(err.message)
              else
                core.setOutput('content', data.toString())
            })
      - name: Patch the description
        uses: kei-g/dockerhub-patch@main
        with:
          description: Debian/Ubuntu with the latest LLVM installed.
          overview: |
            ${{ steps.overview.outputs.content }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repo: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
    strategy:
      matrix:
        dist:
          - bullseye
  ubuntu:
    name: ubuntu:${{ matrix.dist }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Copy Dockerfile
        run: cp docker/linux/${{ matrix.dist }}/Dockerfile ./
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.dist }}
    strategy:
      matrix:
        dist:
          - focal
          - jammy
name: Publish
on:
  workflow_call:
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
  workflow_dispatch:
