env:
  IMAGE_NAME: llvm
jobs:
  latest:
    name: debian:latest
    needs:
      - push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Copy Dockerfile
        run: cp docker/linux/bookworm/Dockerfile ./
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - id: current-time
        name: Format the current time
        run: |
          printf 'value=%s\n' $(date "+%Y%m%d%H%M%S") | tee -a $GITHUB_OUTPUT
      - name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v5
        with:
          build-args: |
            MAJOR_VERSION=${{ inputs.MAJOR_VERSION }}
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:bookworm
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.current-time.outputs.value }}
  patch:
    name: Patch the description to DockerHub
    needs:
      - latest
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    uses: ./.github/workflows/patch.yml
  push:
    name: ${{ matrix.dist }}:${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Copy Dockerfile
        run: cp docker/linux/${{ matrix.name }}/Dockerfile ./
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Run Buildx and Push it to DockerHub
        uses: docker/build-push-action@v5
        with:
          build-args: |
            MAJOR_VERSION=${{ inputs.MAJOR_VERSION }}
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.name }}
    strategy:
      matrix:
        include:
          - dist: debian
            name: bullseye
          - dist: ubuntu
            name: focal
          - dist: ubuntu
            name: jammy
          - dist: ubuntu
            name: lunar
name: Publish
on:
  workflow_call:
    inputs:
      MAJOR_VERSION:
        required: true
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
  workflow_dispatch:
    inputs:
      MAJOR_VERSION:
        default: '18'
        description: >
          Major version of the latest llvm.
        required: true
        type: string
